export const connectorLocalStorageKey = 'connectorId'
export const connectorLocalStorageKeyV2 = 'connectorIdv2'
export const walletLocalStorageKey = 'wallet'
export const connectedKey = 'connected'
export const chainLocalKey = 'chain'
